server:
  port: 8082
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_exercise?useSSL=false
    username: root
    password: 123321
eureka:
  client:
    service-url: #eureka服务器端地址
      defaultZone: http://127.0.0.1:10086/eureka