server:
  port: 8082
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_exercise?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123321
eureka:
  client:
    service-url: #eureka服务器端地址
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  mapper-locations: classpath:mappers/*.xml
swagger:
  application-description: springfox swagger 3.0
  application-name: ${spring.application.name}
  application-version: 1.0
  enable: true
  try-host: http://localhost:${server.port}
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS